Program IncludeEverything;

{
    This file is for use with Identify.  It includes every file
    in the Include: directory.
}

{$I "Include:Devices/GamePort.i"}
{$I "Include:Devices/Audio.i"}
{$I "Include:Devices/Keyboard.i"}
{$I "Include:Devices/HardBlocks.i"}
{$I "Include:Devices/Clipboard.i"}
{$I "Include:Devices/Input.i"}
{$I "Include:Devices/Parallel.i"}
{$I "Include:Devices/TrackDisk.i"}
{$I "Include:Devices/SCSIDisk.i"}
{$I "Include:Devices/BootBlock.i"}
{$I "Include:Devices/PrtBase.i"}
{$I "Include:Devices/InputEvent.i"}
{$I "Include:Devices/PrtGfx.i"}
{$I "Include:Devices/ConUnit.i"}
{$I "Include:Devices/Keymap.i"}
{$I "Include:Devices/Narrator.i"}
{$I "Include:Devices/Timer.i"}
{$I "Include:Devices/Printer.i"}
{$I "Include:Devices/Serial.i"}
{$I "Include:Devices/Console.i"}
{$I "Include:Hardware/Custom.i"}
{$I "Include:Hardware/CIA.i"}
{$I "Include:Hardware/Blit.i"}
{$I "Include:Hardware/DMABits.i"}
{$I "Include:Hardware/ADKBits.i"}
{$I "Include:Hardware/IntBits.i"}
{$I "Include:Resources/Potgo.i"}
{$I "Include:Resources/CIA.i"}
{$I "Include:Resources/FileSysRes.i"}
{$I "Include:Resources/Misc.i"}
{$I "Include:Resources/Disk.i"}
{$I "Include:Resources/MathResource.i"}
{$I "Include:Graphics/Text.i"}
{$I "Include:Graphics/Clip.i"}
{$I "Include:Graphics/Regions.i"}
{$I "Include:Graphics/Copper.i"}
{$I "Include:Graphics/GFXBase.i"}
{$I "Include:Graphics/Display.i"}
{$I "Include:Graphics/Pens.i"}
{$I "Include:Graphics/Sprite.i"}
{$I "Include:Graphics/View.i"}
{$I "Include:Graphics/RastPort.i"}
{$I "Include:Graphics/Areas.i"}
{$I "Include:Graphics/Layers.i"}
{$I "Include:Graphics/Graphics.i"}
{$I "Include:Graphics/GFX.i"}
{$I "Include:Graphics/GraphInt.i"}
{$I "Include:Graphics/Collide.i"}
{$I "Include:Graphics/GELS.i"}
{$I "Include:Exec/Memory.i"}
{$I "Include:Exec/Semaphores.i"}
{$I "Include:Exec/exec.i"}
{$I "Include:Exec/ExecBase.i"}
{$I "Include:Exec/Tasks.i"}
{$I "Include:Exec/ExecName.i"}
{$I "Include:Exec/Interrupts.i"}
{$I "Include:Exec/Devices.i"}
{$I "Include:Exec/ExecOther.i"}
{$I "Include:Exec/Errors.i"}
{$I "Include:Exec/Alerts.i"}
{$I "Include:Exec/Nodes.i"}
{$I "Include:Exec/Resident.i"}
{$I "Include:Exec/Lists.i"}
{$I "Include:Exec/IO.i"}
{$I "Include:Exec/Resources.i"}
{$I "Include:Exec/Ports.i"}
{$I "Include:Exec/Libraries.i"}
{$I "Include:Utils/CRT.i"}
{$I "Include:Utils/TaskUtils.i"}
{$I "Include:Utils/DOSUtils.i"}
{$I "Include:Utils/DeadKeyConvert.i"}
{$I "Include:Utils/IOUtils.i"}
{$I "Include:Utils/BuildMenu.i"}
{$I "Include:Utils/ConsoleIO.i"}
{$I "Include:Utils/ConsoleUtils.i"}
{$I "Include:Utils/MathTransUtils.i"}
{$I "Include:Utils/Random.i"}
{$I "Include:Utils/SameName.i"}
{$I "Include:Utils/RunProgram.i"}
{$I "Include:Utils/StringLib.i"}
{$I "Include:Utils/TimerUtils.i"}
{$I "Include:Utils/Break.i"}
{$I "Include:Utils/DoubleBuffer.i"}
{$I "Include:Utils/Parameters.i"}
{$I "Include:Utils/DateTools.i"}
{$I "Include:Workbench/Startup.i"}
{$I "Include:Workbench/Icon.i"}
{$I "Include:Workbench/Workbench.i"}
{$I "Include:Libraries/MathIEEEDP.i"}
{$I "Include:Libraries/ConfigRegs.i"}
{$I "Include:Libraries/FileHandler.i"}
{$I "Include:Libraries/MathLibrary.i"}
{$I "Include:Libraries/MathFFP.i"}
{$I "Include:Libraries/DOS.i"}
{$I "Include:Libraries/MathTrans.i"}
{$I "Include:Libraries/ConfigVars.i"}
{$I "Include:Libraries/DOSExtens.i"}
{$I "Include:Libraries/DiskFont.i"}
{$I "Include:Libraries/Expansion.i"}
{$I "Include:Libraries/RomBoot_Base.i"}
{$I "Include:Libraries/ExpansionBase.i"}
{$I "Include:Libraries/Translator.i"}
{$I "Include:Rexx/RxsLib.i"}
{$I "Include:Rexx/RexxIO.i"}
{$I "Include:Rexx/Errors.i"}
{$I "Include:Rexx/ARexxStrings.i"}
{$I "Include:Rexx/Storage.i"}
{$I "Include:Intuition/Preferences.i"}
{$I "Include:Intuition/Screens.i"}
{$I "Include:Intuition/IntuitionBase.i"}
{$I "Include:Intuition/Intuition.i"}

begin
end.
